# Generated by Django 5.1.6 on 2025-02-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0002_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='yt_video_url',
            field=models.URLField(null=True),
        ),
    ]
