# Generated by Django 5.1.6 on 2025-02-22 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('yt_learning', '0004_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_watch_later',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userregistrations')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yt_learning.videos')),
            ],
        ),
    ]
