# Generated by Django 5.1.6 on 2025-02-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0005_save_watch_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
