# Generated by Django 5.1.6 on 2025-02-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0007_language_remove_videos_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bashalu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=100)),
            ],
        ),
    ]
