# Generated by Django 5.1.6 on 2025-02-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0008_bashalu'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='bhashalu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yt_learning.bashalu'),
        ),
    ]
