# Generated by Django 5.1.6 on 2025-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0012_codehivelogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codehivelogos',
            name='logo',
            field=models.ImageField(null=True, upload_to='my_logos/'),
        ),
    ]
