# Generated by Django 5.1.6 on 2025-03-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0013_alter_codehivelogos_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeHiveLogos',
        ),
    ]
