# Generated by Django 5.1.6 on 2025-03-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yt_learning', '0020_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
