# Generated by Django 5.1.6 on 2025-04-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('visible_testcases', models.JSONField()),
                ('hidden_testcases', models.JSONField()),
            ],
        ),
    ]
