# Generated by Django 5.1.6 on 2025-04-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeground',
            name='hidden_testcases',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='codeground',
            name='visible_testcases',
            field=models.JSONField(default=list),
        ),
    ]
