# Generated by Django 5.1.6 on 2025-03-19 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('problem', models.TextField()),
                ('input_desc', models.TextField()),
                ('output_desc', models.TextField()),
            ],
            options={
                'ordering': ['problem_id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding_problems.codingproblem')),
            ],
        ),
    ]
